tests/test_copyright.py

We cannot always rely on git to iterate through the files

tests: Iterate files using os.path

---

setup.py

setup: Add setup.py

---

scripts/publish_interactive_plots.py
trappy/plotter/ILinePlotGen.py
trappy/plotter/IPythonConf.py

Improper HTML tags affect the rendering in nbconvert/nbviewer

ILinePlot: Close the Table Tag and add Missing depenedancy 

---

tests/test_stats_grammar.py

tests: Dont assert dataframe index names

---

index.html

Add Link to Interactive Plotter HTML

---

trappy/plotter/AttrConf.py
trappy/plotter/ILinePlot.py
trappy/plotter/ILinePlotGen.py
trappy/plotter/LinePlot.py
trappy/plotter/js/ILinePlot.js

I would actually like to add Dietmar as a watcher. He is not on github yet..

Scatter plots for ILinePlot and LinePlot

---

tests/test_copyright.py

Don't check copyright of files ignored by git

Fix issue #22

---

trappy/__init__.py

Let `trappy.__version__` give you the version number.

trappy: Add version

---

trappy/plotter/js/EventPlot.js

* auto height for the chart depending on number of lanes
* support for guiders (lines used to calculate delta b/w two points)

Enhancements to EventPlot

---

doc/InteractivePlotter.ipynb
trappy/plotter/EventPlot.py
trappy/plotter/__init__.py

Event plot lanes v2

---

trappy/plotter/css/EventPlot.css
trappy/plotter/js/EventPlot.js

We can do a sequential merge of the pull request that have been created in order
#39 #40 and then #41

Context Information for EventPlots

---

index.html

pages: Point to latest EventPlot gist

---

trappy/plotter/ILinePlotGen.py
trappy/plotter/js/ILinePlot.js

plotter: ILinePlot: Allow xlim in ILinePlot

---

trappy/plotter/EventPlot.py
trappy/plotter/IPythonConf.py

plotter: Change URL for d3 installation

---

tests/test_dynamic.py
tests/test_stats_grammar.py
trappy/dynamic.py
trappy/sched.py
trappy/stats/StatConf.py
trappy/stats/grammar.py

Grammar changes v2

---

doc/Run class.ipynb
tests/test_dynamic.py
tests/test_run.py
tests/test_sched.py
trappy/base.py
trappy/cpu_power.py
trappy/devfreq_power.py
trappy/dynamic.py
trappy/pid_controller.py
trappy/plotter/AbstractDataPlotter.py
trappy/plotter/Constraint.py
trappy/plotter/Utils.py
trappy/run.py
trappy/sched.py
trappy/stats/Aggregator.py
trappy/stats/Indexer.py
trappy/stats/Trigger.py
trappy/thermal.py
trappy/utils.py

Run events

---

tests/test_stats_grammar.py
trappy/stats/grammar.py

Event name grammar

---

trappy/stats/grammar.py

Grammar fix v2

---

tests/test_stats.py

Test stats v2

---

trappy/plotter/js/EventPlot.js

Fixing issue #24 for EventPlots

Dynamic resizing for EventPlot

---

trappy/plotter/AttrConf.py
trappy/plotter/ILinePlotGen.py
trappy/plotter/js/ILinePlot.js

plotter: ILinePlot: Responsive Design for ILinePlot

---

index.html

pages: Update for EventPlot and ILinePlot responsive design

---

index.html

Thanks @moinakg for noticing this!
Signed-off-by: Kapileshwar Singh <kapileshwarsingh@gmail.com>

pages: Fix typo on Home Page

---

doc/InteractivePlotter.ipynb

This will serve both for everybody to remember that this is there and as
a soft test that it actually works :grimacing:

doc: add documentation for ILinePlot with generic DataFrames

---

trappy/base.py

With big traces, the `parsed_data` array becomes huge (up to gigabytes).  `parsed_data` is only used as a parameter for `pandas.DataFrame`.  pandas accepts a generator instead of a list.  Therefore instead of creating a huge array for pandas, pass a generator to pandas and let it process the incoming information as it needs to.
Before:
After:
As far as I can tell, `.0` and `data` are internal pandas variable and thus outside of our control.

base: make parsed_data a generator

---

tests/test_plotter.py
trappy/plotter/Constraint.py

Constraint fixes v2

---

tests/test_stats.py
trappy/stats/Trigger.py

Allow trigger filters to be any callable and narrow the data frame with the pivot before applying the filter.

Trigger improvements

---

doc/InteractivePlotter.ipynb
trappy/plotter/ILinePlot.py

ILinePlot: unique x-axis for multiple traces and cleanup v2

---

tests/test_ftrace.py
tests/test_plot_utils.py
tests/test_stats.py
tests/test_wa_sysfs_extractor.py
trappy/plotter/AttrConf.py

Various fixes to remove warnings from the testuite.

Test fixes

---

tests/test_base.py
tests/test_systrace.py
tests/trace_systrace.html
trappy/__init__.py
trappy/cpu_power.py
trappy/devfreq_power.py
trappy/dynamic.py
trappy/ftrace.py
trappy/pid_controller.py
trappy/plotter/__init__.py
trappy/sched.py
trappy/systrace.py
trappy/thermal.py

The three patches on top of this series fixes some issues discovered while reviewing PR #160.
Thus, this series is to be applied after #160 has been merged.

Fixes on top of systrace support

---

README.md

This provides a little improvement for the README. If something is missing let me know and I will add it ;)

README.md: improve structure of README file

---

README.md

Installaion -> Installation
Replaces #170

README.md: fix typo in README

---

README.md

It's cool to point out which version is currently available in pypi.
Report it next to the travis badge.

README: add a pypi badge

---

trappy/__init__.py
trappy/nbexport/__init__.py
trappy/nbexport/preprocessors.py
trappy/plotter/EventPlot.py
trappy/plotter/ILinePlotGen.py
trappy/plotter/IPythonConf.py

Embedded data v3

---

scripts/publish_interactive_plots.py
tests/test_plotter.py
trappy/plotter/ILinePlot.py
trappy/plotter/ILinePlotGen.py
trappy/plotter/IPythonConf.py
trappy/plotter/js/ILinePlot.js

Ilineplot embed data v2

---

tests/test_plotter.py
trappy/plotter/ILinePlot.py
trappy/plotter/ILinePlotGen.py

close #208 
Signed-off-by: Michele Di Giorgio <michele.digiorgio@arm.com>

Fix-indexes v2

---

trappy/plotter/EventPlot.py
trappy/plotter/js/EventPlot.js

The timeline plot was designed to have one "key" running in one "lane".
Here you have the "queueing" key running in multiple lanes and this
confuses the filtering logic. I imagined the each event to be only
present in one lane at a time, much like a single PID can be only on a
single CPU.
This fix allows the EventPlot to plot concurrent events. Events which
occur simultaneously in multiple lanes

EventPlot: Add ability to plot simultaneous events

---

trappy/base.py

Pandas doesn't seem to properly handle running out of memory, and segfaults; this gives you no useful error message.
This error probably isn't too rare, because the default Lisa config only provisions 1Gb of memory in the Vagrantfile. That means a 500k line ftrace file can cause a segfault.
I've added a hacky warning in base.py. Do you think this is appropriate? If not, we could just put this in the documentation and hope people spot the connection, and perhaps something like this hacky warning could go in Lisa instead?

base: Add warning when we're at risk of running out of memory

---

trappy/base.py

This patch reduces the frequency of calling getrusage resulting in a ~3-5%
performance improvement in parsing. We do a check in the beginning and then
check once every 10000 events.
Signed-off-by: Joel Fernandes <joelaf@google.com>

trappy: Improve performance of parser

---

trappy/bare_trace.py
trappy/ftrace.py

Some things broken in the rebase (for caching), fix them.

Trappy cache fixes

---

trappy/ftrace.py

Since `__getattr__` can be called on uninitialized instances (i.e. with no
attributes), it can enter an infinite recursion while trying to access
some instance attributes.
Fix that by ignoring requests for dunder names (`__XXX__`), since they are
resolved without `__getattr__` when needed by a builtin, and are mostly
supposed to be class attributes in other cases. That means `__getattr__`
is not supposed to receive requests to such names often, and these will
(almost) surely not be anything the API can offer since usage of such
names is reserved for future expansion of the language.

ftrace: fix __getattr__ implementation

---

tests/test_base.py
trappy/base.py

Fixes a bug reported by @derkling, details in the commit log.

Hex conversion downtuning

---

trappy/raw_syscalls.py

add parser for raw syscalls (sys_enter / sys_exit)

add support to parse syscall traces
