tests/test_run.py

Workload Automation generate both trace.dat and trace.txt but not the raw
trace.  The sched_switch event (among others) requires raw traces.  Make
sure that the raw trace is generated.

tests: Make sure that trace.raw.txt is generated if both trace.txt and trace.dat exist

---

index.html

TRAPpy's homepage doesn't load correctly in some browsers (eg. Firefox) because of the main page being served over https while some scripts are loaded over an http connection.  Move what we can to https to avoid problems.

Fixes for mixed content in TRAPpy's homepage

---

trappy/plotter/IPythonConf.py

…lots
A request for a "WebResource" is only made is the file is missing on the
host. If there is no connectivity and the file is missing, we should disable
the interactive plots

Fix for #8

---

setup.py

include_package_data is a very nice idea but it just doesn't work.
After installing trappy, importing it failed with:
>>> import trappy
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/local/lib/python2.7/dist-packages/TRAPpy-1.0.0-py2.7.egg/trappy/__init__.py", line 20, in <module>
from trappy.plotter.LinePlot import LinePlot
File "/usr/local/lib/python2.7/dist-packages/TRAPpy-1.0.0-py2.7.egg/trappy/plotter/__init__.py", line 23, in <module>
import trappy.plotter.EventPlot
File "/usr/local/lib/python2.7/dist-packages/TRAPpy-1.0.0-py2.7.egg/trappy/plotter/EventPlot.py", line 40, in <module>
IPythonConf.iplot_install("EventPlot")
File "/usr/local/lib/python2.7/dist-packages/TRAPpy-1.0.0-py2.7.egg/trappy/plotter/IPythonConf.py", line 119, in iplot_install …

setup: fix installation of data files

---

setup.cfg

Tell setuptools where we build the documentation so that "python setup.py
upload_docs" works.

setup: configure upload_docs

---

trappy/plotter/Utils.py
trappy/plotter/__init__.py

This enables the user to filter a plot by PIDs and
execnames. For Example:
trappy.plotter.plot_trace(file, execnames=["task1"])

plotter: Allow filtering in plot_trace

---

trappy/stats/SchedConf.py

get_task_name should use the same fields used by
get_process_for_pids. Fixes issue #46

stats: SchedConf: Fix for get_task_name

---

trappy/run.py

The current error message when trace-cmd is not installed is just "File
not found" without even saying which file is not present, which is very
confusing.  Raise a more meaningful error message if we couldn't find
trace-cmd in PATH.
This fixes #28

run: raise a meaningful error message if trace-cmd is not installed

---

trappy/plotter/EventPlot.py

f4eefc02239a ("plotter: EventPlot: Allow specification of lane names")
reordered the parameters for EventPlot.  Fix the order we have in the
documentation to match the order in the function.
Document summary while we are at it.

plotter: EventPlot: fix the order of the documentation of the EventPlot parameters

---

trappy/stats/SchedConf.py

The period aggregator will now return the list of deltas
between successive start/stops of the task execution.
For issue  ARM-software/bart#26

stats: SchedConf: Fix for period calculation

---

trappy/plotter/__init__.py

To avoid the recreation of the run object for large trace
files. Enhancement #45
Addressing comments in #51

plotter: Accept run objects in plot_trace

---

trappy/sched.py

The following patch align the code for "cpu_frequency" and "cpu_capacity" events. Both of then requires a renaming of the "cpu_id" column to read "cpu". This is required to mix and merge events in the plotter class.

Columns renaming for "cpu_capacity" events

---

trappy/plotter/AttrConf.py
trappy/plotter/LinePlot.py
trappy/plotter/PlotLayout.py

The LinePlotter can generate one or many plots, depending on pivoting
and filters configuration. All these plots usually provides a common view
on a specific set of metrics and/or experiment.
An overall figure title could be useful to better represent what the
set of generated plots refers to.
This patch adds the required support to defined a figure title which can
be defined using an optional new 'title' paramter. For example:
trappy.LinePlot(run, pivot="cpu", title="This is a title").show()
Signed-off-by: Patrick Bellasi <patrick.bellasi@arm.com>

plotter: add support for figure title

---

trappy/sched.py

CPU Frequency and Capacity trace events report the actual "frequency" and
"capacity" using an anonymous "state" column. Plots generated using Plotter
use that columns name in the legend, thus making a bit confusing the plot,
even worst when we want to plot both frequency and capacity.
This patch assigns some more meaningful name to the "state" report by
these two trace events.
Signed-off-by: Patrick Bellasi <patrick.bellasi@arm.com>

run: sched: rename "state" columns for cpu_frequency and cpu_capacity

---

.gitignore

"python setup.py sdist" and friends generate all these folders.  Ignore
them.

gitignore: ignore files generated by setuptools

---

trappy/run.py
trappy/sched.py

A number of trace classes are called as the trace event they parse.
Unsurprisingly, the unique_word *is* the trace event name.  Instead of
repeating the same thing over and over, let register_class() assign a
name to a class it's registering based on the unique_word if it doesn't
have a name.
This needs to be a class variable that's set before the class is
instantiated (Run.register_class() needs it).  So you can't set it in
Base's constructor.  You can't set it in DynamicTypeFactory either
because not every Base class uses that.  This looks like a good
compromise and remove some redundant code.
Change-Id: I6389c9ac072f6571b4faf8dacdee4cd77775a1f8

run: provide a name for the class if there isn't one already

---

tests/test_dynamic.py
trappy/dynamic.py

If the pivot is defined, it should be a string.  If there is no pivot,
then it shouldn't be part of the class variables at all.  Let
register_dynamic() stop registering classes with pivot=None.

dynamic: don't register a class with a None pivot

---

doc/api_reference/conf.py

This is to avoid the error:
<parent_URL> was loaded over HTTPS, but requested an insecure script:
'http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML';.
This request has been blocked; the content must be served over HTTPS.

docs: Update URL path for MathJax

---

tests/test_run.py
trappy/run.py

get_duration should return the same value irrespective of the
normalization of time. Duration is a relative parameter that
measures the length of time from start to the end of the trace

Fix get_duration for normalized time

---

trappy/plotter/EventPlot.py

The current implementation crashes with a ZeroDivisionError
when a key has an empty event list.

plotter: EventPlot: Fix average average calculation

---

tests/test_run.py
trappy/run.py

Add an "add_parsed_event" method to Run  that lets you add a dataframe
to the events in the run.

run: attach events to an existing run event

---

tests/test_stats_grammar.py
trappy/run.py

Accessing the added parsed events fails in the grammar because the class definition for the "Event" is missing.
```
run.pmu_counters.data_frame
from trappy.stats.grammar import Parser
p = Parser(run)
p.solve("pmu_counters:cpu")
````
will not work

Grammar parsed events

---

trappy/stats/Aggregator.py
trappy/stats/Trigger.py

The trigger.generate function needs to return the value
for the valid indices replaced with the trigger value
This value replacement was being handled in Aggregator which
was accessing a private member from the Trigger class.
Removing the _ for making it public was possibly a bad design
choice to make pylint happy.

stats: Fix generation for trigger

---

trappy/plotter/js/EventPlot.js

The plot currently uses the IPython.dialog. This prevents
any future IPython independent uses. This change adds a
simple function to create a dialog body. This is the only
thing we need after all.

plotter: EventPlot: Remove dependency on IPython for JS

---

trappy/plotter/LinePlot.py

In 23724934e98c ("plotter: Pivoted Runs") we broke the titles of
LinePlotter for plots done with column=string.  After that, the titles
for those plots appeared as a comma-separated list of letters:
l,i,k,e,t,h,i,s.
Fix it so that one-column plots display the column as the title and
multi-columns plots display a comma-separated list of columns as title.

LinePlotter: don't make titles appear as t,h,i,s

---

trappy/plotter/js/EventPlot.js

Since the listener needs to fire for each plot on the page
we need to add a namespace to the registered listener. Not
doing doing this causes the resize listener to be fired for
the last created plot. The name-spacing can be done as follows
.on("resize.one", function_one)
.on("resize.two", function_two)

plotter: EventPlot: Namespace the resize event listeners

---

tests/test_base.py
tests/test_dynamic.py
tests/test_ftrace.py
trappy/__init__.py
trappy/dynamic.py
trappy/ftrace.py

The classes registered dynamically in the tests persist across the
execution of the testsuite.  That makes the testsuite sometimes fail if
a test has added a class to the sched scope and
`test_ftrace_has_all_classes_scope_sched` run concurrently.  Unregister
the dynamic events when the tests that register them finish.

Unregister events

---

tests/test_ftrace.py
tests/test_plot_utils.py
tests/test_trappy.py
trappy/ftrace.py
trappy/plot_utils.py

@Leo-Yan reports that `compare_runs()` and `summary_plots()` fail if there's only one actor.  `plot_utils.plot_allfreqs()` raises an exception.

Make plot_allfreqs() work with one actor

---

setup.py

When you install trappy using "pip install" or "python setup.py
install", trappy.EventPlot fails to run because it can't find
EventPlot_help.jpg.  Install it with the rest of the data files.

setup: install EventPlot_help.jpg

---

tests/test_sched.py
tests/trace_sched.txt
trappy/sched.py

Some recent version of trace-cmd prints sched_wakeup and sched_wakeup_new
events using a format string. Thus, when this events are required we must
parse them from the raw trace.
Since these events are already available mainline, this patch pre-register
them dynamically as raw events. This allows to parse these events (when
required) using the proper trace.
The patch adds also a test case by using the original formatted trace as
a source for the raw trace to use.
Signed-off-by: Patrick Bellasi <patrick.bellasi@arm.com>

sched: add classes for wakeup/wakeup_new events

---

tests/test_stats_grammar.py
trappy/stats/grammar.py

Grammar add missing multiplication and exponentiation operators

---

trappy/plotter/AttrConf.py
trappy/plotter/BarPlot.py
trappy/plotter/ILinePlot.py
trappy/plotter/ILinePlotGen.py
trappy/plotter/LinePlot.py
trappy/plotter/StaticPlot.py
trappy/plotter/js/ILinePlot.js

This series uniforms the style of both static and interactive plots. The template is the following:
Where:
- The legend is always shown below the graph, centered with respect to the plot. Notice that in case of static plots we just need a single legend.
- **Master title** is optional. It is shown only if the user provides one.
- **TraceName** in the legend is not shown when is already in the title.
- Background for plots is white.
- Static plots legends have light grey background to better distinguish the labels.
For the interactive plots, there's no possibility to tell the `dygraph` class how many labels to put in the legend, but it is possible to have them one per line. Therefore, they are shown in this way to avoid overlapping of labels when plotting many traces.

Uniform template for static and interactive plots

---

trappy/plotter/js/ILinePlot.js

When plotting with interactive plotter an unnecessary horizontal scrollbar
appears below the chart. It doesn't actually scroll anything. In fact, it is
enough to remove 2 pixels from the figure to get rid of it.
close #152

plotter: ILinePlot: remove undesired horizontal scollbar below plot

---

tests/test_base.py
trappy/ftrace.py

@mdigiorgio got a trace with "[" as part of a task name and that breaks trappy.  This series fixes it and also does some spring cleaning on the `test_parse_special_fields` test

Fix parsing special fields

---

trappy/plotter/js/ILinePlot.js

Apparently in some cases decreasing the figure width by 2 pixels is not
enough. Hence, we subtract one more.

plotter: ILinePlot: decrease figure width by 3 instead of 2

---

tests/test_systrace.py
tests/trace_systrace.html
trappy/__init__.py
trappy/cpu_power.py
trappy/devfreq_power.py
trappy/dynamic.py
trappy/ftrace.py
trappy/pid_controller.py
trappy/sched.py
trappy/systrace.py
trappy/thermal.py

This is v2 of #90 .  A couple of commits only needed minor adaptation and I have retained them.  The test also comes from @derkling (thanks!).  With a new `trappy.SysTrace` class, we should now be able to do `trappy.SysTrace("/path/to/trace.html") and from there be able to use all trappy goodies.

Systrace support

---

.travis.yml
README.md

This in an initial proposal for using Travis CI to run `nosetests` automatically when something new is pushed to the repository.
*NOTE*: in order to run on master it might be necessary that someone with admin rights on ARM-Software enables TRAPpy on Travis.

Travis CI support for continuosly running nosetests

---

.travis.yml

Notifications are sent in case of tests failure only. Anyone interested
in receiving email notifications can add himself to the recipients list.
Since we want to test the just cloned version of TRAPpy we must not
install it using pip.

travis-ci: add email recipients and fix installed packages

---

README.md

We don't advertise the (amazing) documentation that we have.  Let's put
a link in the README to raise awareness.
Move the Quickstart section up while we are at it so that people that
have followed the instructions on how to install it see it straight
away.

README: Add a link to the documentation

---

trappy/plotter/AbstractDataPlotter.py
trappy/plotter/BarPlot.py
trappy/plotter/Constraint.py
trappy/plotter/ILinePlot.py
trappy/plotter/LinePlot.py
trappy/plotter/StaticPlot.py
trappy/plotter/__init__.py

With the introduction of BareTrace and SysTrace, there are a number of
references in the documentation to FTrace that should be more generic,
as classes operate on any of the three *Trace classes.  Update some of
the documentation to reflect this.

plotter: fix references to FTrace

---

trappy/ftrace.py

Having "." as default name for traces was preventing TRAPpy from
assigning a meaningful name, like "Trace 0", to traces for which the
user does not explicitly set a name. As a consequence, every plot with
such traces was showing a dot in the legend and in the title (where
trace name is relevant).
close #168

ftrace: fix default name for traces

---

README.md

We have always implicitly supported Ubuntu 14.04 LTS as the minimum version.
State it explicitly in the README.

README: explicitly state that the instructions are for Ubuntu 14.04 LTS

---

index.html

index.html shows an example of trace parsing, but it uses the now deprecated Run class.
Start using the newer FTrace class to do the same.
Signed-off-by: Juri Lelli <juri.lelli@arm.com>

index.html: use FTrace instead of deprecated Run

---

index.html

Fix a typo in index.html.
Signed-off-by: Juri Lelli <juri.lelli@arm.com>

index.html: fix typo

---

trappy/plotter/IPythonConf.py

On some platforms the profile dir is not in .local/share/jupyter.
We can use the jupyter library functions to find the correct location
for the TRAPpy data and scripts
Signed-off-by: Kapileshwar Singh <kapileshwarsingh@gmail.com>

plotter: IpythonConf: Update method to get profile dir

---

tests/test_plotter.py

This tests checks the following:
- given two data series with different indexes
- ILinePlot will merge them using _fix_indexes
- the set of indexes of the merged series must be the union of the set of
indexes of the initial series

ILinePlot: test independent series merging

---

trappy/plotter/EventPlot.py

When EventPlot embeds the css into the notebook, it adds an extra `\n`
for every line.  `css_fh.readlines()` returns all the lines as an array
but the lines already contain a `\n` at the end of the line.  The
`\n`.join() afterwards adds another `\n`, so you end up with an extra
newline for every line.  Drop the `\n` when reading the css so that it
is embedded without empty lines in between every line in the notebook.

Prettier css

---

scripts/publish_interactive_plots.py

With 85e24151f65a ("plotter: export lib urls to variables") we have a
canonical place for javascript library URLs.  Use them instead of
hardcoding them.

publish_interactive_plots: don't repeat js library URLs

---

trappy/nbexport/__init__.py
trappy/nbexport/exporter.py

nose tries to import all __init__.py files.  Even if you do in
trappy/__init__.py:
try:
import trappy.nbexport
except ImportError:
pass
The testsuite fails because it then goes on and tries to import
trappy/nbexport/__init__.py.  To avoid that, let
trappy/nbexport/__init__.py fail gracefully if it fails to import
anything needing for the export.

trappy: allow running the testsuite in environments without ipython

---

trappy/plotter/ILinePlot.py
trappy/plotter/ILinePlotGen.py

In aa4bece3adc7 ("ILinePlot: don't call data_frame what's just a
python dict") we turned a pd.Series to a dict, because we were
effectively using it as a dict.  However, there was a behaviour change
as a result of this:  pandas series preserve the order of entries
whereas python dictionaries may reorder its entries.  Use an OrderedDict
instead, as that's what aa4bece3adc7 should have done.

ILinePlot: preserve order in the legend of ILinePlot

---

tests/test_stats.py
trappy/stats/Aggregator.py

The prototype of `MultiTriggerAggregator` sets aggfunc to be an optional
parameter (it defaults to `None`).  Fix it so that callers of
`MultiTriggerAggregato`r that don't specify an `aggfunc` actually work and
don't barf:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-141-1fd320357650> in <module>()
----> 1 l = vector_agg.aggregate(level="cluster")
/usr/local/share/trappy/trappy/stats/Aggregator.pyc in aggregate(self, **kwargs)
138         for group in level_groups:
139             group = listify(group)
--> 140             level_res = self._aggfunc(self._result[group[0]], **kwargs)
141
142             for node in group[1:]:
TypeError: 'NoneType' object is not …
```

stats: let MultiTriggerAggregator work without an aggfunc

---

trappy/plotter/Constraint.py

After 9fe317fdb547 ("plotter: fix constraint filtering with multiple
filters and pivots") it is not necessary to handle duplicate indexes in
Constraint any more as we don't need to reindex dataframes.  Kill this
code from Constarint.
Note that this does not kill handle_duplicate_index from trappy, there
are still valid uses in ILinePlot and the grammar.

plotter: Remove handling duplicate indexes from Constraint

---

trappy/plotter/EventPlot.py

requirejs can timeout when loading EventPlot.js in notebooks with many
EventPlots and ILinePlots running in slow machines using Firefox.  As
a result, all EventPlots are empty.  Double the requirejs timeout (the
default is 7s) to give Firefox enough time to execute all the javascript
and load EventPlot.js

EventPlot: increase requirejs timetout

---

trappy/plotter/AttrConf.py

matplotlib's version scheme appends "rcX" to the version for "release
candidate" releases.  However, that's not a valid version according to
distutil's version rules, so StrctVersion raises a ValueError exception:
```
/usr/local/share/trappy/trappy/plotter/AttrConf.py in <module>()
98 colors = ['#348ABD', '#7A68A6', '#A60628', '#467821', '#CF4457', '#188487',
99           '#E24A33']
--> 100 if StrictVersion(matplotlib.__version__) < StrictVersion("1.5.1"):
101     MPL_STYLE['axes.color_cycle'] = colors
102 else:
/usr/lib/python2.7/distutils/version.pyc in __init__(self, vstring)
38     def __init__ (self, vstring=None):
39         if vstring:
---> 40             self.parse(vstring)
41
42     def __repr__ (self):
/usr/lib/python2.7/distutils/version.pyc in parse(self, vstring)
105 …
```

plotter: Cope with matplotlib's version scheme

---

trappy/plotter/EventPlot.py

When we generate the data for EventPlot, we store it in a variable
called "data".  If there are two plots in a notebook and the notebook is
copied (or the page reloaded), the second "data" variable clobbers the
first one, so when requirejs gets round to execute EventPlot.generate(),
all EventPlots use the same data.
We don't really need to store the data in a variable, we can just pass
it straight to EventPlot.generate()

EventPlot: Don't use a variable for the data

---

tests/test_plotter.py
trappy/plotter/AbstractDataPlotter.py

When you try to plot a dataframe without specifying the column, the code that checks it fails with
```
KeyError: "column"
```
Fix the check so that the appropriate error (`ValueError: Column not specified for DataFrame input`) is printed.

plotter: show appropriate error when plotting a dataframe but column was not specified

---

trappy/plotter/ILinePlot.py
trappy/plotter/ILinePlotGen.py

This is v2 of #203.  When creating huge plots, ILinePlot can make the browser choke. Prevent it by rasing an exception if the user is trying to create a plot that can hang their browser.

ILinePlot: avoid generating plots that can hang the browser

---

doc/InteractivePlotter.ipynb
tests/test_constraint.py
trappy/plotter/Constraint.py
trappy/plotter/ILinePlot.py
trappy/plotter/StaticPlot.py

xlim limits the x axis to a given range, but for ILinePlot we pass all the data to dygraph and then let dygraph apply the window.  That means that we include a lot of useless data in the notebook and we lose performance parsing data that will never be plotted.
Improve xlim for ILinePlot so that it only embeds the data relevant for the plot.

ILinePlot: only pass the necessary data when xlim is passed

---

trappy/plotter/EventPlot.py

_get_lanes() does some changes to the input data that are necessary for the
Javascript code to work properly. However, these changes permanently affect the
input data. In particular, "lane" names are converted to integers.
To avoid this, let's create an internal copy of the input data and always
operate on that.
Signed-off-by: Michele Di Giorgio <michele.digiorgio@arm.com>

plotter: EventPlot: avoid changes on input data by operating on a copy

---

doc/InteractivePlotter.ipynb
trappy/plotter/EventPlot.py
trappy/plotter/js/EventPlot.js

Give the possibility to specify a mapping between events and custom colours in
the plot.
User can specify colours as both colour name or using its HEX representation.
Signed-off-by: Michele Di Giorgio <michele.digiorgio@arm.com>

plotter: EventPlot: add user-defined color map

---

tests/test_stats_grammar.py
trappy/stats/grammar.py

Parser() operations happens across the whole event.  While it is possible to filter the events and add them back to the trace object with `.add_parsed_event()`, it is a kludge that we could remove by bringing the concept of filters from the plotters to here.
With this change, we can simplify this:
ftrace = trappy.FTrace(trace_fname)
sbt_dfr = ftrace.sched_boost_task.data_frame
boost_task_rtapp = sbt_dfr[sbt_dfr.comm == rta_task_name]
ftrace.add_parsed_event("boost_task_rtapp", boost_task_rtapp)
analyzer = Analyzer(ftrace, {})
analyzer.assertStatement("blah")
To:
ftrace = trappy.FTrace(trace_fname)
analyzer = Analyzer(ftrace, filters={"comm": "rta_task_name"})
analyzer.assertStatement("blah")
This fixes #145

grammar: apply filters to data accesses

---

.travis.yml

Travis is failing to run the tests because it is trying to use TK for plotting, which is not present in the environment:
```
======================================================================
ERROR: Test that plotter handles triplicates fine
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/travis/build/ARM-software/trappy/tests/test_duplicates.py", line 95, in test_plotter_triplicates
per_line=3)
File "/home/travis/build/ARM-software/trappy/trappy/__init__.py", line 28, in __init__
raise exc
ImportError: No module named _tkinter, please install the python-tk package
```
See https://travis-ci.org/ARM-software/trappy/builds/157597148 for the full log.
Installing the python-tk package doesn't solve the issue because you …

travis-ci: Don't fail if there isn't an X server running

---

trappy/sched.py

`sched_migrate_task` has been in the kernel since v2.6.28.  Let's add it to the events in the sched scope.

sched: add sched_migrate_task to the list of automatically parsed sched events

---

trappy/stats/grammar.py

The `Parser` documentation defines pvars a couple of times but it doesn't
pass it to the `Parser` object itself.  Fix the examples so that they
handle it.
While we are at it, simplify the dictionary generation.

grammar: fix Parser documentation

---

trappy/ftrace.py

window is inclusive: https://github.com/ARM-software/trappy/blob/master/trappy/ftrace.py#L197
I don't think this matters in practice when using traces off Linux targets, but while working on a test with a synthetic time-series I needed to know.

ftrace: Note in documentation that `window` is inclusive

---

trappy/idle.py

This means that when you use a trappy.stats.grammar.Parser to solve
"cpu_idle:state" you get a DataFrame with CPUs as columns, each row
showing the idle state of each CPU at a given time.

idle: Add pivot name for cpu_idle parser

---

trappy/stats/grammar.py

If you typo a trace event name in a call to Parser.solve, you currently get a
KeyError from trying to access the result of globals(); the stacktrace goes
through a pyparsing callback to str_to_attr via _pre_process ("""Pre-process
accessors for super-indexing""")...
Add an exception with a message to hint at what went wrong.

stats/grammar: Raise meaningful error when asked to parse bad event

---

tests/test_stats_grammar.py
trappy/stats/grammar.py

If you use the Parser to access events that Trappy understands, but that are not
present in the trace, you currently get an inscrutable exception when trying to
access `.loc[ self._window[0]:]` on the empty DataFrame in _get_data_frame.
Ideally attempting to parse absent events would just return an empty DataFrame,
but then we don't know what columns it should have. So instead let's just raise
a more helpful error saying that the event is not present.

stats/grammar: Raise helpful error when asked to parse absent events

---

tests/test_base.py
tests/trace_equals.txt
trappy/base.py

If a trace field value contains a '=', we currently get a ValueError('Too many
values to unpack'). Instead, let's only split on the first '='.
In practice if a field value contains a '=' it's probably because a kernel
developer typo'd a custom event like:
/* Note missing space between "%d" and "bar" */
trace_printk("my_broken_event: foo=%dbar=%d", foo, bar)
So I did consider raising an explicit 'malformed event field' error. But this
approach is more flexible in case someone really wanted to trace fields
containing strings with '=' in them.

base: Don't error on event field values containing '='

---

.travis.yml

travis-ci: Use IPython below v6.0.0 to avoid Python 3.3 requirement

---

tests/test_ftrace.py
tests/test_systrace.py
trappy/bare_trace.py

Classes that implement the generate_data_dict method have an additional argument
to the signature. This leads to errors in case the base class method is called
with the additional argument.

bare_trace: fix signature of generate_data_dict

---

trappy/ftrace.py

There are some issues with caching at the moment which I haven't been
able to debug but that are confirmed as affecting multiple
people. Until we can find the time to fix the issue, let's disable
caching by default.

ftrace: Disable caching by default

---

tests/test_baretrace.py
tests/test_ftrace.py
trappy/bare_trace.py

The previous implementation only looked at the maximum timestamp
of the traces. However, if trace windows are used to analyse a
subset of the full trace, get_duration() would return an
erroneous value:
(times are normalized)
trace = <trace built with window=[5, 10]>
print trace.get_duration()
> 10.0
This commit adds a lower-bound lookup to fix this issue.

bare_trace: Fix get_duration() for window use

---

tests/test_caching.py
tests/test_common_clk.py
tests/trace_common_clk.txt
trappy/common_clk.py

Traces from clock_set_rate, clock_enable, clock_disable need
specialized parsing. Add additional feature to parse these traces.
Test: run the 3 new unit tests (nosetests tests/test_common_clk.py)
Change-Id: Ib93b72697fc4d5eb30cffb914bbe0cb4c4cd872d

parse traces from the common clock infrastructure

---

tests/test_caching.py
tests/test_filesystem.py
tests/trace_filesystem.txt
trappy/filesystem.py

Adds trace parsing for ext4_da_write_begin, ext4_da_write_end,
ext4_sync_file_enter, and ext4_sync_file_exit events
Test: run the 4 new unit tests (nosetests tests/test_filesystem.py)
Change-Id: I9b7049d5e9879cc3dedb5fd9d3d1433fa8304618

parse traces from ext4 events

---

tests/test_caching.py
tests/test_ftrace.py
tests/trace_sched.txt.cache/md5sum
tests/trace_sched.txt.cache/metadata.json
trappy/ftrace.py
trappy/systrace.py

I've been struggling to reproduce the bugs generated by caching (I did encounter them in the past so I'm not doubting their existence), as such I mostly went through the code and improved what I thought needed to be improved.
I'm not re-enabling caching in this PR, but I will try to convince some people to re-enable it on their side and do some bug-finding for me.

Caching: factorizing / toughening

---

tests/test_caching.py
trappy/base.py

By default, the str to float conversion done when reading from csv is
different from the one used when reading from the trace.txt file.
Here's an example:
- trace.txt string timestamps:
[76.402065, 80.402065, 80.001337]
- parsed dataframe timestamps:
[76.402065000000007, 80.402065000000007, 82.001337000000007]
- csv string timestamps:
[76.402065, 80.402065, 80.001337]
- cached dataframe timestamps:
[76.402064999999993, 80.402064999999993, 82.001337000000007]
To fix this, the timestamps read from the cache are rounded
to microsecond precision, which results in cache-read timestamps
being identical to trace-read timestamps.
Tests have also been added/tweaked to ensure this stays true.

ftrace: Homogenize timestamps conversions

---

trappy/plotter/ILinePlotGen.py

You currently have to specify a 'group' for the 'zync_zoom' parameter
to work. However a likely use case is to plot multiple signals with a
single ILinePlot call, and need them to be zoom-synced. For
example, suppose we want to plot the frequency of all CPUs
in a trace, on separate axes with zoom synced:
ILinePlot(ftrace, signals='cpu_frequency:frequency',
pivot='cpu', drawstyle='steps-post',
sync_zoom=True, group='my_group').view()
Here the use of 'my_group' seems unnecessary since it only
occurs in one place.
Therefore use a hash of the ILinePlotGen object by default. This will
make the above example work with 'group' omitted.

ILinePlot: Add default group for zoom sync

---

tests/test_base.py
tests/trace_failed_to_parse.txt
trappy/__init__.py
trappy/base.py
trappy/exception.py
trappy/ftrace.py

Some events from the kernel cannot be parsed by old trace-cmd
binaries. This results in data_str starting with "[FAILED TO PARSE]",
which we ourselves fail to parse because we expect to find a
key=value pair.
This adds a missing 'continue' statement to avoid attempting to avoid
a KeyError when attempting to use an unset prev_key as a key into
data_dict, and also adds a special error for the "[FAILED TO PARSE]"
case.

base: Improve errors for failures to parse

---

tests/test_ftrace.py
tests/trace_no_trailing_line.txt
trappy/ftrace.py

We currently strip off the last character under the assumption that it is a
'\n'. However it isn't always. So use rstrip to do that instead.

ftrace: Fix parsing textual traces with no trailing line

---

tests/test_caching.py
tests/test_filesystem.py
tests/trace_filesystem.txt
trappy/filesystem.py

Adds trace parsing for the f2fs_write_begin, f2fs_write_end,
f2fs_sync_file_enter, and f2fs_sync_file_exit events.
Test: run the 4 new unit tests (nosetests tests/test_filesystem.py)
Change-Id: Ic9a77ea4c29c10de0538e4a9d2e6b20d6dc85064

parse traces from f2fs events

---

tests/test_sort.py
tests/trace_idle_unsorted.txt
trappy/ftrace.py

In the unlikely event that a trace event of a given class ends up
appearing AFTER it happened (IOW, its timestamp is *before* the
previous event in the report/dataframe), we'll hit this error:
``` python
File "/home/valsch01/Work/lisa/libs/trappy/trappy/ftrace.py", line 732, in __init__
window, abs_window)
File "/home/valsch01/Work/lisa/libs/trappy/trappy/ftrace.py", line 100, in __init__
self._do_parse()
File "/home/valsch01/Work/lisa/libs/trappy/trappy/ftrace.py", line 309, in _do_parse
self._apply_user_parameters()
File "/home/valsch01/Work/lisa/libs/trappy/trappy/ftrace.py", line 286, in _apply_user_parameters
self._windowify_class(trace_class, self.max_window)
File "/home/valsch01/Work/lisa/libs/trappy/trappy/ftrace.py", line 166, in _windowify_class
window[0]:]
File …
```

ftrace: Ensure dataframe indexes are monotonic

---

tests/test_caching.py
tests/test_fallback.py
tests/test_ftrace.py
tests/test_systrace.py
trappy/fallback.py
trappy/ftrace.py

Respin of:
https://github.com/ARM-software/trappy/pull/276
Changelog:
* Modified the exception system when accessing the wrong attribute. It is now handled by `GenericFTrace.__getattr__` instead of introducing an new class. That also allows catching issues earlier.
* Removed a RuntimeError that could apparently not happen (i.e. having the class accessible as an attribute named with the unique_word, at the same time as being available under the class name, with the class name being different from the unique_word)

trappy: Add support for 'print:' ftrace fallback event [v2]

---

tests/test_base.py
tests/test_caching.py
tests/test_cpu_power.py
tests/test_fallback.py
tests/test_ftrace.py
tests/test_plot_utils.py
trappy/base.py
trappy/cpu_power.py
trappy/fallback.py
trappy/ftrace.py

Remove Print event class since it interferes with "tracing_mark_write" matching. Print event has been introduced very recently in the library and no external code base is using it yet.
Also add a sanity check on unique words to make sure that they are never a substring of another one.

Remove print event

---

.travis.yml

Matplotlib doesn't install in travis due to an old version of pip:
Matplotlib 3.0+ does not support Python 2.x, 3.0, 3.1, 3.2, 3.3, or 3.4.
Beginning with Matplotlib 3.0, Python 3.5 and above is required.
This may be due to an out of date pip.
Make sure you have pip >= 9.0.1.
In travis, pip is picked from the python2 virtualenv.  Upgrade the it
to the latest version of python2 to fix the issue.

travis: update python2 to 2.7.15

---

setup.py
trappy/utils.py

We've had this one for a few months now:
trappy/utils.py:78: FutureWarning: 'get_duplicates' is deprecated and will be removed in a future release. You can use idx[idx.duplicated()].unique() instead
dups = index.get_duplicates()
Do what the warning says.

trappy: utils: Fix get_duplicates FutureWarning

---

trappy/base.py

Because it relied on str.isdigit(), Base.string_cast() would
erroneously assume a hex string (e.g. "0x42") wouldn't be castable to
int.
Use a more robust pattern using try/except blocks. This will happily
cope with negative and hex values.
While at it, rename string_cast() to string_cast_int(), since the
former only handles ints and does an ugly empty return when the
specified type isn't int.

base: Fix string to int conversion

---

tests/test_ftrace.py

In Python2, iterating over a dict's keys will always give the same
sequence (although the ordering is arbitrary). In Python3 that
ordering is still abitrary, but to make things even better it can
change from one execution to another.
GenericFTrace.get_all_freqs_data() returns a list who's ordering
depends on the keys of the input dictionnary. That in itself would
need to be changed to a better design, but for the time being we can
fix the test and make Trappy pass reliably by using an OrderedDict.

tests/test_ftrace: Fix test_get_all_freqs_data()

---

tests/test_idle.py
trappy/base.py
trappy/stats/grammar.py
trappy/utils.py

When running Lisa tests on fastmodels duplicated timestamps happen
frequently and cause some failures down the line.
The duplicated timestamps are not bad themselves and a side effect of
simulated time not having good enough resolution.
Handling this duplication at the dataframe creation seems to be the most
generic and future proof solution.
Signed-off-by: Qais Yousef <qais.yousef@arm.com>

base.py: handle any duplicated indices when creating dataframe

---

trappy/base.py

Under the hood pandas represents numeric values as NumPy ndarrays and
stores them in a continuous block of memory. Values of the same column
are represented using the same type and thus number of bytes.
Many types in pandas have multiple subtypes that can use fewer bytes to
represent each value. For example, the float type has the float16,
float32, and float64 subtypes.
Use the function pd.to_numeric() to downcast numeric types to use for
each value the minumum number of bytes which is still enough to
represent the maximum value for a given column.
Use also "Categoricals" introduced in Pandas since version 0.15.
The category type uses integer values under the hood to represent the
values in a column, rather than the raw values. Use category to
efficiently compress the representation of …

trace/base: Optimizing DataFrame memory footprint

---

trappy/ftrace.py

The timestamp of consecutive events are sometimes the same, if they were emitted
in a very short interval of time. This becomes an issue when the events are
dispatched in separate dataframes, which then sometimes need to be joined back
together in client code. At this point, the ordering between events can be lost,
leading to wrong results when exact ordering is required.
In order to fix that, pick the next representable floating value when there is
an ambiguity. This ensures that the delta added is the smallest possible, and is
typically in order of 1e-11.

ftrace: Ensure timestamp uniqueness

---

trappy/function_graph.py

These events are generated by the function_graph tracer on function entry and
exit.
Signed-off-by: Douglas RAILLARD <douglas.raillard@arm.com>

ftrace: Add support for funcgraph_entry and funcgraph_exit events

---

trappy/function.py

The non-raw version of this event is of the shape
"CALLEE <-- CALLER"
which trappy obviously doesn't like. Force this event to be parsed raw,
which gives us:
ip=<addr> parent_ip=<addr>

ftrace: Add support to parse function tracing ('function' tracer)
